loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  auth_enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 50Gi

memberlist:
  service:
    publishNotReadyAddresses: true
