cluster:
  name: kind-test-argo

destinations:
  loki:
    type: loki
    url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

collectors:
  alloy-logs:
    enabled: true

  alloy-metrics:
    enabled: true

metrics:
  enabled: true
  collector: alloy-metrics
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  podMetrics:
    enabled: true

clusterEvents:
  enabled: true
  collector: alloy-logs
  namespaces:
    - monitoring
    - org1-prod
    - ingress-nginx

podLogs:
  enabled: true
  collector: alloy-logs
  gatherMethod: kubernetesApi
  namespaces:
    - monitoring
    - org1-prod
    - ingress-nginx

nodeLogs:
  enabled: false
